# Use a base image with Node.js installed
FROM node:14-alpine

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json to the container
COPY package*.json ./

# Install dependencies
RUN npm install --production

# Copy the application code to the container
COPY . .

# Set the environment variables
ENV PORT=3000
ENV DATABASE_URL="mongodb+srv://jiabdelaziz:CplIoJf5KC1X3TsU@cluster0.u97eu4a.mongodb.net"
ENV DATABASE_NAME="Bikeshare"
ENV STRIPE_SECRET_KEY="sk_test_51NCZkbGy0kbFHoHStTfHmPIK1xCF2aMZZOUxccZOPct3dhprBZyldyDB2xtBpOfmHOGfsR4BlIUlv8b29OMVlgDI00pmktSwMw"

# Expose the port that the microservice will listen on
EXPOSE $PORT

# Start the microservice
CMD ["node", "index.js"]
